"""add album_entries group/time_label/views/notes columns

Revision ID: 5f510ca52271
Revises: 80edfad82f0a
Create Date: 2026-09-13 21:48:16.601795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f510ca52271'
down_revision: Union[str, Sequence[str], None] = '80edfad82f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_entries', sa.Column('group_name', sa.String(length=128), nullable=True))
    op.add_column('album_entries', sa.Column('time_label', sa.String(length=64), nullable=True))
    op.add_column('album_entries', sa.Column('views', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('album_entries', sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album_entries', 'notes')
    op.drop_column('album_entries', 'views')
    op.drop_column('album_entries', 'time_label')
    op.drop_column('album_entries', 'group_name')
    # ### end Alembic commands ###
