"""add album_entries table

Revision ID: 80edfad82f0a
Revises: 8618a21f952b
Create Date: 2026-09-13 21:33:45.937943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80edfad82f0a'
down_revision: Union[str, Sequence[str], None] = '8618a21f952b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('attachment_ids', sa.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_album_user_taken_at', 'album_entries', ['user_id', 'taken_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_album_user_taken_at', table_name='album_entries')
    op.drop_table('album_entries')
    # ### end Alembic commands ###
