"""add memories.source column

Revision ID: 8618a21f952b
Revises: 99b375a29b41
Create Date: 2026-09-12 10:48:25.123288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8618a21f952b'
down_revision: Union[str, Sequence[str], None] = '99b375a29b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('source', sa.String(length=16), server_default=sa.text("'auto'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'source')
    # ### end Alembic commands ###
