"""add memories table for long-term memory

Revision ID: 99b375a29b41
Revises: 745d7b794b91
Create Date: 2026-09-11 22:55:18.772798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '99b375a29b41'
down_revision: Union[str, Sequence[str], None] = '745d7b794b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('owner_agent_id', sa.String(length=64), server_default=sa.text("'companion'"), nullable=False),
    sa.Column('memory_type', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('importance', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('source_message_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('superseded_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('access_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['superseded_by'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memories_embedding', 'memories', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_memories_user_status', 'memories', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_memories_user_status', table_name='memories')
    op.drop_index('idx_memories_embedding', table_name='memories', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('memories')
    # ### end Alembic commands ###
