"""add messages.api_session

Revision ID: bb3dd4c0689d
Revises: 24b22370f42f
Create Date: 2026-09-09 10:57:33.524754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3dd4c0689d'
down_revision: Union[str, Sequence[str], None] = '24b22370f42f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('api_session', sa.String(length=64), nullable=True))
    op.create_index('idx_messages_api_session', 'messages', ['api_session'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_api_session', table_name='messages')
    op.drop_column('messages', 'api_session')
    # ### end Alembic commands ###
